version: '2.0'

services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443 
    volumes:
      - ../bbs-vue/dist/newbee/:/etc/nginx/html
      - ./logs/nginx/:/var/log/nginx
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - newbee
    networks:
        - new_bee
  mysql:
      image: mysql:5.6.35
      container_name: mysql
      ports:
        - "3307:3306"
      volumes:
        # - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
        - ./logs/mysql/:/var/log/mysql/:rw
        - ./config/mysql/:/var/lib/mysql/:rw #加载 mysql 默认配置
      environment:
        MYSQL_USER: "root"
        MYSQL_PASSWORD: "123"
        MYSQL_ROOT_PASSWORD: "123" 
      networks:
        - new_bee
        
  newbee:
    restart: always
    image: java:openjdk-8-jre-alpine
    container_name: newbee
    volumes:
        - ../bbs-java/target/:/opt/app
        # - ./logs/java/:/opt/app/
    # expose:
        # - 8083
    ports:
       - 8003:8003
    depends_on:
       - mysql
    links:
        - mysql
    networks:
        - new_bee
    command: java -jar /opt/app/newBee-0.0.1.jar >> /opt/app/log/newBee.log & tail -f /opt/app/log/newBee.log

networks:
  new_bee:
    driver: bridge
