version: '2.0'

services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx-test
    ports:
      - 80:80
      - 443:443
    volumes:
      - /bbs/newbee/:/etc/nginx/html
      - ./logs/:/var/log/nginx
      - /bbs/nginx.conf:/etc/nginx/nginx.conf:ro


  mysql:
      image: mysql:5.6.35
      container_name: mysql-test
      ports:
        - "3306:3306"
      volumes:
        # - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
        - ./logs/:/var/log/mysql/:rw
        - /mysql/:/var/lib/mysql/:rw #加载 mysql 默认配置
      environment:
        MYSQL_USER: "root"
        MYSQL_PASSWORD: "123"
        MYSQL_ROOT_PASSWORD: "123"
      # networks:
      #   - net-mysql
 